<?php
define('EMAIL','M.Sleem@egynass.net');
define('PASS','');
  require("phpmailar/PHPMailer.php");
  require("phpmailar/SMTP.php");
            require 'PHPMailerAutoload.php';
            // require '../vendor/autoload.php';
            //Create a new PHPMailer instance
            $mail = new PHPMailer;
            //Tell PHPMailer to use SMTP
            $mail->isSMTP();
            //Enable SMTP debugging
            // SMTP::DEBUG_OFF = off (for production use)
            // SMTP::DEBUG_CLIENT = client messages
            // SMTP::DEBUG_SERVER = client and server messages
            // $mail->SMTPDebug = SMTP::DEBUG_SERVER;
            //Set the hostname of the mail server
            $mail->Host = 'smtp.gmail.com';
            // use
            // $mail->Host = gethostbyname('smtp.gmail.com');
            // if your network does not support SMTP over IPv6
            //Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
            $mail->Port = 587;
            //Set the encryption mechanism to use - STARTTLS or SMTPS
            // $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            //Whether to use SMTP authentication
            $mail->SMTPAuth = true;
            //Username to use for SMTP authentication - use full email address for gmail
            $mail->Username = 'Sales@egynass.net';
            //Password to use for SMTP authentication
            $mail->Password = 'Zz123456++';
            //Set who the message is to be sent from
            $mail->setFrom($_POST['email'], $_POST['name']);
            //Set an alternative reply-to address
            $mail->addReplyTo($_POST['email'], $_POST['name']);
            //Set who the message is to be sent to
            $mail->addAddress('M.Sleem@egynass.net');
            //Set the subject line
            $mail->Subject = $_POST['name'];
            //Read an HTML message body from an external file, convert referenced images to embedded,
            //convert HTML into a basic plain-text alternative body
            // $mail->msgHTML(file_get_contents('contents.html'), __DIR__);
            //Replace the plain text body with one created manually
            $mail->Body = 'You have message from :'.$_POST['name']."\r\n".
            'Phone : '.$_POST['phone']."\r\n".
            'Message : '.$_POST['message'];
            //Attach an image file
            // $mail->addAttachment('images/phpmailer_mini.png');
            //send the message, check for errors
            if (!$mail->send()) {
                echo 'Mailer Error: '. $mail->ErrorInfo;
            } else {
                // echo 'Message sent!';
                header('Location: ' . $_SERVER['HTTP_REFERER']);

                //Section 2: IMAP
                //Uncomment these to save your message in the 'Sent Mail' folder.
                #if (save_mail($mail)) {
                #    echo "Message saved!";
                #}
            }


            // $mail = new PHPMailer;
            // $mail->IsMail(); // telling the class to use MAIL

            // $mail->SMTPAuth = true;
            // $mail->Username = 'Sales@egynass.net'; //paste one generated by Mailtrap
            // $mail->Password = 'Zz123456++'; //paste one generated by Mailtrap
            // $mail->Port = 465;

            // $mail->setFrom( $_POST['email'], $_POST['name']);
            // $mail->addAddress('M.Sleem@egynass.net');
            // $mail->Subject  = $_POST['name'];
            // $mail->Body= 'You have message from :'.$_POST['name']."\r\n".
            // 'Phone : '.$_POST['phone']."\r\n".
            // 'Message : '.$_POST['message'];
            // if(!$mail->send()) {
            //   echo 'Message was not sent.';
            //   echo 'Mailer error: ' . $mail->ErrorInfo;
            // } else {
            // header('Location: ' . $_SERVER['HTTP_REFERER']);

            // }



?>